version: '3.5'

services:
  server:
    ports:
      - 8000:8000
    build:
      context: ./server
    volumes:
      - ./server:/var/www/html
      - ./server/vendor/:/var/www/html/vendor/
    command: php -S server:8000 -t public
    restart: always
  web:
    container_name: web
    build:
      context: ./web
    volumes:
      - ./web:/app
      - /app/node_modules
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true